### PR TITLE
Add event to rowMouseOut and rowMouseOver callback

### PR DESCRIPTION
**Pull request by morsdyce**
This exposes the rowMouseOver and rowMouseOut event, this is mainly because sometimes you need additional information other than which row is hovered.

For example, showing a tooltip with data related to the row you hovered on.

### CODE REVIEW

**Comment by AllenFang** [comment]
LGTM :+1:   Thanks your contribution :)

**Comment by morsdyce** [comment]
Would appreciate if this could be merged and released soon if possible.

Thanks!

**Comment by AllenFang** [comment]
@morsdyce, sorry for waiting. I've released on ```v2.0.3```

**Comment by morsdyce** [comment]
@AllenFang Thank you very much!

You didn't keep me waiting, you did it in incredible speed. 

Thanks again!

**Pull request merged**
