### PR TITLE
Multiple sorting for columns

### PR DESCRIPTION
**Pull request by sameersemna**
Hallo Allen, this PR has Multiple sort for columns and also the resizable headers, merged and ready with your latest master branch

### CODE REVIEW

**Comment by AllenFang** [comment]
@sameersemna, I think separate this PR as two is better for me to review and make some modified, maybe a PR for resizable column and another one is for multiple column sorting. 

BTW, I saw there's some commits is for table footer, could you please remove it?  just one PR is focus on one thing :)

and I found you always merge my upstream on every PR, maybe you can fetch upstream and then start to work 

I'll close this issue, and wait you separated PR. Anyway, you did a great job, it's very awesome, thanks 👍

**Comment by AllenFang** [comment]
hello, @sameersemna, did you have giiter?  may I talk with you? Thank you :)

**Comment by sameersemna** [comment]
hello, @AllenFang sure we can talk
apologies for the late reply, I was on vacation in India
I joined your Gitter room today.

**Comment by AllenFang** [comment]
@sameersemna, ok I'll find you in this weekend. 👍

**Pull request closed without merging**
