### PR TITLE
Original

### PR DESCRIPTION
**Pull request by sameersemna**
Adding table footers, testing footers in tabs.

### CODE REVIEW

**Comment by AllenFang** [comment]
Due to this PR, I'll close https://github.com/AllenFang/react-bootstrap-table/pull/822 and review this one.

**Comment by AllenFang** [comment]
hi @sameersemna, did you have any idea to make ```tfooter``` fixed? currently, I wanna to merge this branch, but i think a fixed footer under the table is necessary for user

**Comment by sameersemna** [comment]
Hi Allen, I have made the footers sticky and the body scrollable, I have also added resizable columns, please check. I have added a demo for that as well.

**Comment by AllenFang** [comment]
@sameersemna, that's awesome :)  I'll check this out. Thank you!

**Comment by AllenFang** [comment]
@sameersemna, that's awesome you did very lots of contribution. I need spend some time to review it. Because there's some many changes, so if you can give a list to describe what's feature you did and what's part you improved will be very helpful :)

Thanks 👍

**Comment by AllenFang** [comment]
@sameersemna, like https://github.com/AllenFang/react-bootstrap-table/pull/886. I think we should make thing simple and pure, As my consideration, this PR also include resizable, multiple sort and table footer, is painful for me to review and test, so I'm gonna close this PR and wait you open a PR only for table footer.

Thanks again :100:

**Pull request closed without merging**
