### PR TITLE
replace PropTypes with `prop-types` library to remove warnings

### PR DESCRIPTION
**Pull request by SidKwok**
@AllenFang Jobs done!

### CODE REVIEW

**Comment by AllenFang** [comment]
Thanks, I'm going to close the legacy one and will review this PR soon, thanks

**Comment by okmyomar** [comment]
@SidKwok perfect now we will have proptypes, and I you should take a look the file /src/BootstrapTable.js  between the lines 1414 and 1421, there are some "React.PropTypes." in the code

**Comment by SidKwok** [comment]
@okmyomar  oh, I didn't realize that. I will check all the files and make a new PR.

**Comment by AllenFang** [comment]
thanks @okmyomar

**Comment by AllenFang** [comment]
It was released on `v4.0.0-beta.5`

**Pull request merged**
