### PR TITLE
Improvement custom text filter

### LINKED ISSUE #548: How to set text value in TextFilter component?
I want to use TextFilter to filter data, using  params in URL as text value in TextFilter.
I notice there is a 'dafaultValue' in table options, but it works only initialize phase.
How to set text value in TextFilter component, so i can filter data dynamically.

### PR DESCRIPTION
**Pull request by madeinfree**
This PR want to resolve #548 and #470 problem, I exposed the filterHandler by onCustomHandleTextFilter api.
# **First**
options: onCustomHandleTextFilter(filter :filterHandler, value :defaultValue)

set onCustomHandleTextFilter props in your TableHeaderColumn like
```
function customHandleTextFilter(filter, value) {
  // dynamic params
  filter(value, 'TextFilter');
}

<BootstrapTable data={ products }>
  <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
  <TableHeaderColumn dataField='name' filter={ { type: 'TextFilter', delay: 1000, defaultValue: window.location.hash, customHandleTextFilter: customHandleTextFilter } }>Product Name</TableHeaderColumn>
  <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
</BootstrapTable>
```

# **Second**
options: clearFilter :boolean
if you set 
```
<TableHeaderColumn dataField='name' filter={ { type: 'TextFilter', clearFilter: true } }>Product Name</TableHeaderColumn>
```
then TextFilter will auto clear, when you after typed.

### CODE REVIEW

**Comment by AllenFang** [comment]
thanks @madeinfree, I'm busy on my job, I'll review it in next weekend. 👍

**Comment by madeinfree** [comment]
@AllenFang, thanks for your effort Allen, when you have some features wanna to do or something needed, feel free to assign me :D

**Comment by AllenFang** [comment]
thanks you very much. I'll tell you on slack :)

**Comment by madeinfree** [comment]
@AllenFang OK, Welcome 👍🏻

**Comment by AllenFang** [comment]
@madeinfree, About #470, #595 has tackled it, actually, the requirement for #470 is hope to clean all the filter **programmatically**, so I think the auto clear is not a well idea and it will make user feel the inconsistency on the data if filter cleaned. Anyway, I'll remember this auto clear mechanism, if someone ask, I can just apply your branch.

And #548, still the same condition, user hope we can provide a mechanism that could be called to apply the filter condition **programmatically**, so that's why he said the ```defaultValue``` only work on init phase. for this issue, I'll try to follow #595's way to implement for all the filter, not only text filter.

So close this PR. Anyway, 
because you help me a lots on this project, so just I've added your name to my appreciation list on README.md.

Thanks your contribution :)  Hope you can keep to contribute this repo 👍

**Pull request closed without merging**
