### PR TITLE
updated react-router version and locked history version to 1.17.0

### PR DESCRIPTION
**Pull request by staminaloops**
Fixed:

https://travis-ci.org/AllenFang/react-bootstrap-table/builds/99513015
```
'npm ERR! peerinvalid The package history@1.12.5 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@1.0.3 wants history@^1.17.0'
```

This is the way of doing it for now according to this issue: https://github.com/rackt/react-router/issues/2682

Also, relative to fbjs@^0.3.1 included from react-toastr, there is already a pull request here:
https://github.com/tomchentw/react-toastr/pull/44

We just have to upgrade react-toastr when that PR is merged.

### CODE REVIEW

**Comment by staminaloops** [comment]
Well seems that travis is no longer showing an error.

**Comment by tomchentw** [comment]
@staminaloops I've just released [react-toaster@2.3.0](https://github.com/tomchentw/react-toastr/releases/tag/v2.3.0).

**Comment by NullDivision** [comment]
Hah. You beat me to it @tomchentw :grin:

**Comment by staminaloops** [comment]
@tomchentw @NullDivision Thank you!

**Comment by AllenFang** [comment]
@staminaloops @tomchentw, Thanks for helping. I'll close this PR on next version :ship:

**Comment by NullDivision** [comment]
Can we have an ETA on when that's gonna happen? :)

**Comment by AllenFang** [comment]
@NullDivision, sorry, it's hard to say, but next version will be released in a day or two :)

**Comment by AllenFang** [comment]
Released on <code>v1.4.0</code> :ship:

**Comment by NullDivision** [comment]
:+1:

**Pull request merged**
