### PR TITLE
Add paginationPosition option

### PR DESCRIPTION
**Pull request by garlab**
This option allows to set the position of the pagination bar:
- 'top' will position it on top, between the table and the toolbar
- 'bottom' (default) will position it below the table (current behaviour).
- 'both' will display two pagination bar, one on top and the other on the bottom.

### CODE REVIEW

**Comment by AllenFang** [comment]
@garlab, because of ```v3.0.0``` is on developing, and this release is focus on customizable for components(e,g. pagination, toolbar.) so I wont merge this PR but hope you can reopen another PR and change target into branch of ```v3.0.0-dev```. I'll think about your solution and decide whether to merge it.

**Comment by AllenFang** [comment]
BTW, thanks your contribution, You did a great job :100:

**Comment by AllenFang** [comment]
Ref to #497, dont forgot this PR

**Comment by garlab** [comment]
@AllenFang Thanks for your feedback, I will reopen it in v3.0.0-dev shortly.

**Pull request closed without merging**
