### PR TITLE
Ability to sort on multiple columns

### PR DESCRIPTION
**Pull request by varak69**
Clicking on a column will sort the table. Clicking on another column will sort the table with the new column as highest sort priority and the previous column as the second sort priority for duplicate entries in the new column.

### CODE REVIEW

**Comment by AllenFang** [comment]
@varak69, thanks, I'll check this out!

**Comment by gReis89** [comment]
@varak69 are you thinking on supporting default sorting for multiple columns either? I mean, a new option to send a list of default columns which should be sorted in order.

**Comment by varak69** [comment]
@gReis89 Yes, that's a great idea. I'll add that when I get the chance.

**Comment by AllenFang** [comment]
@varak69, can you done this job in near future, I ready to start review and merge your code.

**Comment by varak69** [comment]
@AllenFang, sorry for the delay. Been busy with the new year and all. I've added the default sort functionality.

**Comment by AllenFang** [comment]
hi @varak69, happy new year and thank your contribution, BTW, I've already refactoring your PR on my local and support the default sort and sort management externally. I'll release the newest version today or tomorrow. and will introduce the commits that i done, thanks 👍

**Comment by varak69** [comment]
Ah, excellent. Thank you very much! :+1:

**Comment by AllenFang** [comment]
Multi column supported on ```v2.9.0```, Following are few example:
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/multi-sort-table.js
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/manage-multi-sort-external-table.js

Thanks @varak69's contributions.

**Comment by Laggii** [comment]
Will it appear in 3.0.* beta also?

**Comment by AllenFang** [comment]
yap, I'll release ```v3.0.0-beta.7``` in this weekend.

**Pull request closed without merging**
