### PR TITLE
add a select class on selection of a row

### PR DESCRIPTION
**Pull request by LensArt**
add an additional class if a row is selected. This can be used io the background color.

### CODE REVIEW

**Comment by AllenFang** [comment]
@LensArt, Thanks your contributions :) But I think you should patch the source code for me.

**Comment by LensArt** [comment]
@AllenFang Ok I am not sure what you mean? You want this kind of patch? https://patch-diff.githubusercontent.com/raw/AllenFang/react-bootstrap-table/pull/159.patch
Or what should I provide you with?

**Comment by AllenFang** [comment]
@LensArt, you should modify the <code>./src/TableRow.js</code> instead of <code>./lib/TableRow.js</code>. Because under <code>lib</code> folder is all the bundled files not the source code

**Comment by LensArt** [comment]
Oops :# I fixed it in another PR :)

**Pull request closed without merging**
