### PR TITLE
add configurable toolbar fixes #1540

### LINKED ISSUE #1540: Configurable Positioning of the Toolbar
Options to move the toolbar to the top, bottom, or both.  Same as Pagination

### PR DESCRIPTION
**Pull request by bryon-czoch**

### CODE REVIEW

**Review by AllenFang — CHANGES_REQUESTED** [review]
There're some conflict in `BootstrapTable.js`, please have a look, thanks your contributions 👍

**Comment by AllenFang** [comment]
@bryon-czoch thanks, I'll check this soon 👍

**Comment by bryon-czoch** [comment]
👍

**Review by AllenFang — APPROVED** [review]

**Comment by AllenFang** [comment]
Released on `v4.0.2`, thanks again

**Pull request merged**
