### PR TITLE
Remove deprecated .getDOMNode() calls

### PR DESCRIPTION
**Pull request by jrsquared**
React 0.14 does not need .getDOMNode() anymore, and it's use pollutes the console pretty heavily.

### CODE REVIEW

**Comment by AllenFang** [comment]
HI @jrsquared , thanks your contributions :) but currently, I dont want to modify these depreacted api and merge into <code>master</code>. So I will leave this PR for a time and merge it in near future. :)

**Comment by fmr** [comment]
:+1:

**Comment by informa** [comment]
:+1:

**Comment by escane** [comment]
Love to see it get merged!

**Comment by jrsquared** [comment]
Updated the PR with changes from master...

**Comment by fmr** [comment]
Hi @AllenFang, it looks like the project has a hard dependency on react 0.14.0, which means the changes to the [dom node refs](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#dom-node-refs) are already in place.

@jrsquared's PR *fixes* the issue of getting a lot of warnings from calling ``.getDOMNode()``, which shouldn't be used anymore. IMHO, the master branch is in a broken state, and this PR will put it back on the right track.

Thanks for this very useful package and keeping it up to date!

**Comment by AllenFang** [comment]
ok, I'll merge it first today,  thanks your feedback :)

**Pull request merged**
