### PR TITLE
enhance expand row - added indication about expanded rows

### PR DESCRIPTION
**Pull request by dekelb**
PR for #1039

### CODE REVIEW

**Comment by AllenFang** [comment]
@dekelb, I'll check this out and this patch may not be merged immediately, I'm busy in near future. BTW, could you please run an example which enable row selection, cell edit and your expand row indicator, an check if functionality are still work well together. If you find a bug and you dont know how to solve it, that's find, I can help you

Anyway, thanks your contributions, great job

**Comment by dekelb** [comment]
Thanks for your comment @AllenFang ! I added the examples to the `expandRow` examples, everything works there. I didn't add the expand to the editCell, but I just did now a double check regrading this and everything works there.

**Comment by AllenFang** [comment]
@dekelb, thanks

**Comment by AllenFang** [comment]
Released on `v3.1.0`, thanks again for your contribution :)

**Comment by dekelb** [comment]
@AllenFang can you please also merge this pr also into the v2 branch?
I'm currently using v2.11.2 and it will take some time to check that everything works in v.3.

Thanks!

**Comment by AllenFang** [comment]
I'll create a branch named as `v2.11.2` and could you please open again into this branch? because `master` currently have all the code about `v3.0.0` and this is very huge.

**Comment by dekelb** [comment]
For some reason github doesn't give me the option to create a pull request from my branch to your v2.11.2

**Comment by AllenFang** [comment]
of course, I'll spend some time to do it, but I think upgrade to newest version will be better.

**Comment by dekelb** [comment]
I've manage to upgrade from v2 to v3 so It's not needed anymore (unless someone else need this feature in v2).

Thanks anyway :)

**Comment by AllenFang** [comment]
👍

**Pull request merged**
