### PR TITLE
Updated modules' version

### PR DESCRIPTION
**Pull request by jkomyno**

### CODE REVIEW

**Comment by AllenFang** [comment]
thanks @jkomyno, it's really big changes, especially the ```babel``` and ```react-router```. I'll spend some time to review this. Anyway, thanks a lots

**Comment by AllenFang** [comment]
@jkomyno, because eslint and babel has been upgraded by this patch, but you still need to configure the .eslintrc and make all lint pass, for the babel, you have to re configure the .babelrc and install another babel package, if you still have interesting to path this PR, please let me know.

**Comment by jkomyno** [comment]
Uh ok, I'll take a look asap. Would you please mind suggesting the most proper way to handle this?

**Comment by AllenFang** [comment]
@jkomyno, it's very complicated to be done(Hard to said), so, I suggest you dont change the eslint related dependency. 

Also, you can change the babel, but you have to make the babel@6 compatible with this repo.
BTW, if you dont have free time to do, I'll handle it in this weekend based on your PR 

Thanks :)

**Comment by madeinfree** [comment]
@jkomyno @AllenFang I'll try to upgrade babel version 6 in this weekend.

**Comment by AllenFang** [comment]
Close this issue, cause of we have already upgrade the modules(ex: ```react-router```, ```babel```, ```history```). But eslint not yet.

**Pull request closed without merging**
