### PR TITLE
RE: #72 Get pagination&sort params

### PR DESCRIPTION
**Pull request by AllenFang**

### CODE REVIEW

**Comment by AllenFang** [comment]
#99

**Comment by luqin** [comment]
Hi, @AllenFang 
It's time to choose a test framework(jest or karma) to make sure the code work good.

**Comment by AllenFang** [comment]
HI @luqin , you right, It's important to test this component. But I really really have no time to do it ;( Hope I have 48hr in one day. I prefer use karma and mocha, how did you think? If we start to write testing code, I think we need have a plan at first.

**Comment by luqin** [comment]
@AllenFang 你有QQ吗？可以加一个交流交流

**Comment by AllenFang** [comment]
@luqin, no, just email, or facebook or  google+

**Comment by luqin** [comment]
那我关注你的 facebook 吧

**Comment by AllenFang** [comment]
https://www.facebook.com/shaochang.fang

**Comment by AllenFang** [comment]
I have added you!

**Comment by luqin** [comment]
:+1:

**Pull request merged**
