### PR TITLE
Add an option to customize the "Select" text on SelectFilter filter.

### PR DESCRIPTION
**Pull request by eitansela**
Add selectText as a prop to filter prop.
An example:
 <TableHeaderColumn ref='nameCol' dataField='quality' filterFormatted dataFormat={ enumFormatter }
              formatExtraData={ qualityType } filter={ { type: 'SelectFilter', options: qualityType, selectText: 'Choose' } }>Product Quality</TableHeaderColumn>

### CODE REVIEW

**Comment by AllenFang** [comment]
@eitansela, thank you :)  But It’s a pity that I release a new version at few minutes ago...  so this PR will be merged on next version.  

Anyway, thanks your contribution. Great job 👍

**Comment by eitansela** [comment]
Hello @AllenFang , When is the next version expected?
Thanks,

**Comment by AllenFang** [comment]
This weekend or next week :)

**Comment by AllenFang** [comment]
@eitansela, merged and released on ```v2.5.8```

**Comment by eitansela** [comment]
Thanks!

**Pull request merged**
