### PR TITLE
use yarn, upgrade react-router v3, fixed issue

### PR DESCRIPTION
**Pull request by madeinfree**
Hi @AllenFang, 
# Yarn install

This is PR with yarn and dependencies fix
## Install yarn

``` command
> npm install yarn --global
> yarn
```
# Fixed dependencies issue
## React, React Bootstrap

use react version 15.3.0 cause PropTypes[#7132](https://github.com/facebook/react/pull/7132) issue from react-bootstrap v0.29.5 so I upgrade react-bootstrap v0.30.0[#2095](https://github.com/react-bootstrap/react-bootstrap/pull/2095) to resolve this issue.
## React Router

I try to upgrade react-router to avoid history dependencies issue by version 3.0.0([link](https://github.com/ReactTraining/react-router/blob/v3.0.0/package.json#L35)) which use `history` dependencies itself, so we can didn't care about `history` dependencies.

use 

``` javascript
import { hashHistory } from 'react-router' 
//and add props into
<Router history={ hashHistory }>
```

now react-router 3.0.0 working fine.
# Now dependencies version
1. react-bootstrap v3.0.6
2. react-router v3.0.0
# Test working version

react, react-dom: 0.14.7, 15.0.0, 15.3.0 (all pass)

Have some suggestion feel free to discussion with me 👍

### CODE REVIEW

**Comment by AllenFang** [comment]
@madeinfree, thanks a lot, it all look great for me but I still have few question about dependency, why move the ```react-bootstrap``` and ```history``` to ```dependencies``` section. In my opinion, ```react-bootstrap-table``` should not depend on these packages.

**Comment by madeinfree** [comment]
@AllenFang sorry it my fault, I fixed the dependency

**Comment by AllenFang** [comment]
Very appreciated that you can still contribute this repo until now. :octocat:

**Comment by AllenFang** [comment]
Thanks your contribution 👍

**Comment by AllenFang** [comment]
#497

**Pull request merged**
