### PR TITLE
Update react-bootstrap-table.css

### PR DESCRIPTION
**Pull request by konekoya**
1. Remove unnecessary px unit after value 0.
2. Some minor tweaks for code consistency.

### CODE REVIEW

**Comment by AllenFang** [comment]
Thanks you :)

**Comment by konekoya** [comment]
No problem! wanted to help but just not sure where to start.. Let me know if there's anything that I can help with.

**Comment by konekoya** [comment]
@AllenFang Thanks for the tips on how to get stated with it! In fact, I have used it in one of my projects. It's easy to pick up and integrate with React based projects. I will try to run the examples and gain a deeper understanding of it.

For the table scrollbar issue. I think I might able to come up with some solutions. But I would like to discuss with you in person on 11/19 during your short visit in Hsinchu. Just wanted to ensure that I understand your problem correctly. Plus lots of React questions that have bothered me for quite a while.

**Comment by AllenFang** [comment]
> But I would like to discuss with you in person on 11/19 during your short visit in Hsinchu.

ok 👍

**Comment by konekoya** [comment]
Great! See you then.

**Comment by AllenFang** [comment]
Merged on ```v2.5.7```. Thanks your contribution 👍

**Pull request merged**
