### PR TITLE
adding grand total

### PR DESCRIPTION
**Pull request by venkat-vs-id**
Hi I have added the logic to show the grand total to the code. 
I have also changed the existing examples to check if the total logic works or not.
1) Basic table : A basic react-bootstrap-table
2) Table Sort: Table Sort Example
3) column filter : Text Filter Example

I still have to clean the code and make it production ready. But first i thought i will run it past you and if you think the changes I have made and you want me to go ahead and make the code prod ready.

Please let me know

### CODE REVIEW

**Comment by AllenFang** [comment]
> I have also changed the existing examples to check if the total logic works or not.

you can add a new one instead of changing.

Anyway, it look good for me at first saw and I think you can keep to refactor your code, I'll review and do some change after you completing if necessary.

Thanks 👍

**Comment by jfernandogt** [comment]
Hello @venkat-vs-id  do you have news about this? I am interesting in this feature.

**Comment by venkat-vs-id** [comment]
Hi @jfernandogt _ need the grand total for my reports and i needed it ASAP, so i took the source and made little changes to get what I wanted. 

check this - https://github.com/venkat-vs-id/react-bootstrap-table

If you run the examples you will see grand-total examples for 
1. Basic table : A basic react-bootstrap-table
2. Table Sort: Table Sort Example
3. column filter : Text Filter Example

**Comment by AllenFang** [comment]
@venkat-vs-id, I also wanna have this feature, but I need to review it and test it, btw, you said you will have a code clean and production ready, but I didn't saw any commits, anyway, I'm going to pull  your branch and clean your code the test it after chinese new year, but it really need some time, because `v3.0.0` already forward to production after chinese new year also. 

I'll work hardly 👍

**Comment by AllenFang** [comment]
I've reviewed a lots of table to see how them implement the summary on table footer, for `react-bootstrap-table`, I need a easy use and more customizable functionality and we also need to solve the vertical scrollbar issue if footer exists. So I decide to delay this feature after `v3.x.0` and find a better way to support this feature, the solution of this PR is not very well for customize the footer and not very intuitive to use. So I decline this issue and really thanks @venkat-vs-id's contributions, you did a great job

**Pull request closed without merging**
