### PR TITLE
Make Cell Read Only

### PR DESCRIPTION
**Pull request by bennnjamin**
This is to implement a new option on the `editable` property for Table Columns as discussed in Issue #1154. 

`editable` now accepts a property `readOnly` which when set to `true` will make the column read only (i.e. disable cell editing). The current implementation of setting `editable` to `false` will prevent **disable column input for adding a new row**. 

This is useful if you want to implement `INSERT` but not `UPDATE` on your Table.

### CODE REVIEW

**Comment by AllenFang** [comment]
I'll spend some time to review your PR

**Comment by bennnjamin** [comment]
The dist folder came from cloning the master branch. I have since updated the fork to not include those folders

**Comment by bennnjamin** [comment]
I added the`dist` folder back, please check now.

**Comment by AllenFang** [comment]
Released on `v3.1.6`, thanks your contributions :)

**Comment by bennnjamin** [comment]
Thanks for merging this!

**Pull request merged**
