### PR TITLE
Fixed searching with filteredData

### PR DESCRIPTION
**Pull request by jfougere**
Currently the search is not working while data is being filtered. 
The following line is incorrect:
`const source = this.filterObj !== null ? this.filter(this.filterObj) : this.data;`
because this.filter(this.filterObj) does not return data but only update filteredData

### CODE REVIEW

**Comment by AllenFang** [comment]
hi @jfougere, sorry for lately reply, I'll check this out :)  thanks your contributions

**Comment by jfougere** [comment]
hi @AllenFang did u had the time to review the PR ? 
thanks

**Comment by AllenFang** [comment]
@jfougere, I'll review it in these day, but need sometime, because the combination of search and filter is very annoying

**Comment by jfougere** [comment]
@AllenFang yes I understand. I saw the comment about the double filter. I did not improve that part, just made a direct fix of the current code.

**Comment by AllenFang** [comment]
Actually, I'm thinks about how to avoid the bug from #363 again.

**Comment by jfougere** [comment]
Hi @AllenFang any news ? Any chance to first integrate this little fix ? ;)

**Comment by AllenFang** [comment]
@jfougere, I've fix this issues and also #457 and it's under testing, I'll released in this week. BTW, I may close this PR cause I fix #457 and this issue by a better way.

**Comment by jfougere** [comment]
@AllenFang perfect! You can close this PR so.

**Comment by AllenFang** [comment]
I've fixed this issue and released on ```v2.3.3```. Anyway, thanks your contribution :) You did a great job

**Pull request closed without merging**
