### PR TITLE
With this PR, the BootstrapTable can now support remote data.

### PR DESCRIPTION
**Pull request by dana2208**
It supports the following features in an external source of data:
- filtering
- searching
- sorting
- pagination
- adding a row
- deleting a row
- exporting to CSV

### CODE REVIEW

**Comment by AllenFang** [comment]
oh my god, the biggest one features is coming....  Thanks a million a lots.... 
BTW, because your commit is only one, so could you please give me a simple introduction for How do you fetch data from remote? with other library?


thanks again..

**Comment by dana2208** [comment]
Hi!

You're welcome :+1: 
I gave a lot of examples in the remote folder. The last example combines everything.

Here is how I implement the remote data with the BootstrapTable:
I am using composition: a react element represents my store that is responsible for fetching, organizing (sorting, filtering...) and manipulating (add, remove) the data. This data is in the state of the store and each time this data is updated the render method is executed. In the render method I use another react component that takes as a props the data and will create the BootstrapTable.

Into the store, you can work with any data source you want: an array, a JSON file, a database...

Personally I use Meteor platform so I am working with a reactive datasource which is a cursor on my mongo collection. I am tracking some reactive variables into my store (like the filter, or the sorting) and each time they change, this updates the data state of the store which is passed as a props to my inner react component responsible for creating the BootstrapTable.

It really looks like the example I provided in the remote folder, but with Meteor platform and tools (like ReactiveVar and Tracker autorun).

**Comment by dana2208** [comment]
Hi,

I made a new commit fixing a demo issue and fixing a bug. Please check my commit comment.

**Comment by AllenFang** [comment]
@dana2208, thanks, I'll review it :)

**Comment by dana2208** [comment]
Hi @Allen

**Comment by dana2208** [comment]
Hi @AllenFang, did you review this PR? 
Thanks!

**Comment by AllenFang** [comment]
@dana2208, I'll merge it quickly, it's busy in recent.  Sorry :)

**Comment by AllenFang** [comment]
@dana2208, I've released on ```v2.3.0```. Sorry for lately merged :)

**Pull request merged**
