### PR TITLE
Remove deprecated react.propTypes, now using prop-types package

### PR DESCRIPTION
**Pull request by okmyomar**
React.propTypes is deprecated, is important to start using the prop-types package as recommended in the react official docs.

"Note: React.PropTypes is deprecated as of React v15.5. Please use the prop-types library instead."
From: https://facebook.github.io/react/docs/typechecking-with-proptypes.html

### CODE REVIEW

**Comment by okmyomar** [comment]
Did you other detail, please let me know if just removing dist folder from the PR it can go ahead to do it, thanks!

**Comment by AllenFang** [comment]
@okmyomar, maybe you can revert your commit? but if you dont know how to do it, I think I can handle it before merging, thanks

**Comment by AllenFang** [comment]
Thanks a lots 👍

**Comment by AllenFang** [comment]
@okmyomar, could you do me a favor?? I want you to change the target branch from `master` to `react-s-alert`. Actually, `react-s-alert` is v4.0.0 branch.

I want to release your branch on `v4.0.0`.

**Comment by AllenFang** [comment]
I think you can just change your target branch, don't delete it

**Comment by AllenFang** [comment]
@okmyomar, would you open again but change target to branch of `v4.0.0-dev`? I'm ready to release `v4.0.0`. thanks a lots.

**Comment by okmyomar** [comment]
@AllenFang  I was kind of bussy these days, but I see there is a new PR with that update (=

**Comment by Fralleee** [comment]
Any update on v4.0.0 release?

**Comment by AllenFang** [comment]
@Fralleee, sorry for lately updated, I'll release `v4.0.0` ASAP, thanks

**Pull request closed without merging**
