### PR TITLE
feature - use tab to change edit row

### PR DESCRIPTION
**Pull request by madeinfree**
Features for #876, try /examples/cell-edit 👍 

tab-to-cell-edit

### CODE REVIEW

**Comment by AllenFang** [comment]
@madeinfree, That's pretty awesome, maybe I can base this PR to support this table with a excel-like moving with table also. Thanks your contributions 👍

**Comment by madeinfree** [comment]
Good works 👍

**Comment by AllenFang** [comment]
Released, https://github.com/AllenFang/react-bootstrap-table/releases/tag/v3.0.0-beta.11

Thanks your contributions

**Comment by dekelb** [comment]
If already supported I think it will be nice to also have the shift+tab to go back to the previous tab. Since the general functionality is already there I think it would be very easy to implement.

**Comment by madeinfree** [comment]
@dekelb Yes, thanks for your remind, I can help this if need it.

**Comment by dekelb** [comment]
It's not something that I need, but I really think it will make this feature complete.

**Comment by AllenFang** [comment]
I'll consider to add this in the future. Thank

**Pull request merged**
