### PR TITLE
Added code for custom buttons

### PR DESCRIPTION
**Pull request by mbaroukh**
Hi,

I just added the ability to put custom buttons in the toolbar.

You can see it in action here :
https://www.baroukh.com/nb/react-bootstrap-table-doc/#/examples/custom

I needed it for a project and it is enough for me but if this pull request is ok for you, I'll take time to link (if asked) those buttons to currently selected lines so the action can occur on specific rows.

Thanks for this library !

Mike

### CODE REVIEW

**Comment by mbaroukh** [comment]
I should have added a code example ...
custom buttons are just an object passed to BootstrapTable :

```javascript
const customButtons = [
      {
        text: 'Display an alert',
        handler: () => alert('Custom button Clicked')
      },
      {
        text: 'Do not click here !',
        handler: () => alert('You, bad boy !'),
        bsStyle: 'warning',
        icon: 'alert'
      }
    ];
    return (
      <BootstrapTable
          data={ products }
          customButtons={ customButtons }>
        <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
        <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
        <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
```

**Comment by AllenFang** [comment]
@mbaroukh, that's awesome, it's a good improvement. But you know, there're a lot of issues which hope they can add not only button but also select, field,, etc. So I've planned to start work for ```v3.0.0```, you can check #497. I think I will make these component(insert button, search field, toolBar.. etc)  become React components and export to user, just let user have more ability to customize these components. So will not merge this PR.

Anyway, Thanks your contribution :100:  You did a great job :)

**Comment by tarim** [comment]
Hi @mbaroukh ,

I tried to use your code with latest master branch, and it doesn't work for me. any idea please?

**Comment by mbaroukh** [comment]
Hi @tarim .
Which code do you tried ? The sample above ? It is relative to a pull request (https://github.com/AllenFang/react-bootstrap-table/pull/528/commits/464ecdea4bee6bd0361a080ac386ffb36e0c4634) that will not be merged.
Custom buttons will be in v3 (cf https://github.com/AllenFang/react-bootstrap-table/issues/497) but if you need custom buttons now you can use my patch until v3 is out.

**Comment by tarim** [comment]
Hi @mbaroukh ,

Yes, I did exactly you described on your code, but somehow the custom button did not show up on my page. I have no idea why.

Thanks,

**Comment by zRaspina** [comment]
Hi @mbaroukh,
I need custom button, is it exist in new version now?

**/CC:** @AllenFang

**Comment by AllenFang** [comment]
@zRaspina, check https://github.com/AllenFang/react-bootstrap-table/issues/497#issuecomment-260108434, you can check the examples for how to custom the buttons.

The ```v3.0.0-beta``` already released, the newest version is ```v3.0.0-beta.6```.

**Comment by zRaspina** [comment]
@AllenFang, I can't find related example about custom buttons. Can you post link here man? 😉

**Comment by AllenFang** [comment]
https://github.com/AllenFang/react-bootstrap-table/tree/v3.0.0-dev/examples/js/custom

**Pull request closed without merging**
