### PR TITLE
datetime-local type option for cell edit

### PR DESCRIPTION
**Pull request by sekharp**
Hi Allen, let me know how these changes look to add a datetime-local input option for cell editing, and if there's anything else I can include to make this pull request successful. Thanks! Love your project.

### CODE REVIEW

**Comment by AllenFang** [comment]
@sekharp, thanks your contribution, I'll spend some time to review this PR :)

**Comment by sekharp** [comment]
Sounds good Allen, let me know if there's anything else I can include or explain here.

**Comment by AllenFang** [comment]
@sekharp , ok, I'll review this PR in these day :) thanks you 👍

**Comment by sekharp** [comment]
awesome, thank you Allen!

**Comment by AllenFang** [comment]
@sekharp, merged and released on ```v2.4.1```. Thanks your contribution :)

**Pull request merged**
