### PR TITLE
Fix wrong url routes and add possibility to custom "Save" and "Close" button

### PR DESCRIPTION
**Pull request by Glognus**
Hey !

Just fixed the wrong urls from "others" directory.

### CODE REVIEW

**Comment by AllenFang** [comment]
@Glognus, thanks :+1:

**Comment by Glognus** [comment]
I added possibility to custom text button "Save" and "Close".
Like cutstom insert text button :
```
const options = {
  insertText: 'Ajouter',
  deleteText: 'Suprimer',
  saveText: 'Sauvegarder',
  closeText: 'Annuler'
};
```

**Comment by AllenFang** [comment]
@Glognus, great, I'll check this out:)

**Comment by AllenFang** [comment]
@Glognus, I dont see any patch on custom "Save" and "Close" button. Did you patch it directly in dist files?

**Comment by Glognus** [comment]
@AllenFang Yes i added it in dist files, it doesn't work ?

**Comment by AllenFang** [comment]
@Glognus, you should fix on source files not dist files. did you want to keep to fix it? if yes, I suggest you open another PR, because I've merged this in my local. Anyway, remember up date your patch on **source files**. Thanks:)

**Comment by Glognus** [comment]
@AllenFang No problem, i will fix it, thanks ;)

**Comment by AllenFang** [comment]
@Glognus, this fixing has been released on ```v2.3.1```.

**Pull request closed without merging**
