### PR TITLE
Adding features to use colSpan and rowSpan in a table header

### PR DESCRIPTION
**Pull request by sumbad**
This features let us use properties  `colSpan` and `rowSpan` with `row`. In the `row` properties sets number of header row. For example:

```
      <BootstrapTable data={ products }>
        <TableHeaderColumn row='0' rowSpan='2' dataField='id' isKey={ true } >ID</TableHeaderColumn>
        <TableHeaderColumn row='0' colSpan='2'>Product</TableHeaderColumn>
        <TableHeaderColumn row='1' dataField='name'>Name</TableHeaderColumn>
        <TableHeaderColumn row='1' dataField='price'>Price</TableHeaderColumn>
      </BootstrapTable>
```

Here our header will be with two rows and with merged cells. How we can see in `<TableHeaderColumn row='0' colSpan='2'>Product</TableHeaderColumn>` we skip `dataField`. It's possible here because this row has a subheader but isn't necessary.

**By default `row='0'`, `colSpan='1'`, `rowSpan='1'` and we can skip them.**

To show how it work I added a file examples/column/column-header-span.js
This PR addresses #519

### CODE REVIEW

**Comment by AllenFang** [comment]
@sumbad that's a cool feature, I'll review it in these day. Thanks your contribution 👍

**Comment by AllenFang** [comment]
@sumbad, I've check your code and you did a great job. Unfortunately, we lose some feature(sort, filter ) on the span column, but I think it's ok, we can patch these feature in the future. 

But there's still some bug, you can try following example:
```js
export default class ColumnHeaderSpan extends React.Component {
  render() {
    return (
     <BootstrapTable data={ products }
        selectRow={ selectRow }
        cellEdit={ cellEdit }
        insertRow deleteRow exportCSV>
        <TableHeaderColumn row='0' rowSpan='2' dataField='id' isKey={ true } >ID</TableHeaderColumn>
        <TableHeaderColumn row='0' colSpan='2'>Product</TableHeaderColumn>
        <TableHeaderColumn row='1' dataField='name'>Name</TableHeaderColumn>
        <TableHeaderColumn row='1' dataField='price'>Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}
```
Which I enable a lots of features, but they all have some bugs, you can try it.

If you have time, hope you can fix it, I'll leave this PR open until we fix all the issue. BTW, I think this PR is very worth to merge, so after ```v3.0.0``` release, I'll spend some time to fix these bugs.

Thanks, feel free to discuss with me :)

**Comment by sumbad** [comment]
Hello @AllenFang! Thanks a lot, I'll try to fix it.

**Comment by ricogabunada** [comment]
Hi @sumbad and @AllenFang ,

Any updates about this issue? I want to use this feature :D. Thank you very much!

**Comment by AllenFang** [comment]
@ricogabunada, this issue still have bugs which need to be solved first. I'll release ```v3.0.0``` in near future, after that, I'll jump into this PR to fix bugs but it really need some times.

**Comment by ricogabunada** [comment]
@AllenFang okay. thanks!

**Comment by sumbad** [comment]
Hi @AllenFang , I have done some changes in code. Now your above example works fine :)
I checked:
- select rows;
- csv export; 
- insert rows.

Additionally I added new examples for Column Header Span in  /examples/js/column-header-span/

P.S. I'm so awfully sorry for so much commits. They have been added after a command `git rebase master` in my branch.

**Comment by AllenFang** [comment]
@sumbad, thanks, I'll check how you fix these bugs. You did a great job 💯

**Comment by mattparrilla** [comment]
A bit late to the party, but I was just going to put in a request for this feature. Perhaps I can offer some help.

I'm not sure how much work has gone into this so far and the ship might have sailed, but have you considered something like this?

```js
<BootstrapTable data={data}>
    <TableHeaderGroup label="Name">
        <TableHeaderColumn dataField="firstName">First Name</TableHeaderColumn>
        <TableHeaderColumn dataField="lastName">Last Name</TableHeaderColumn>
    </TableHeaderGroup>
    <TableHeaderGroup label="About">
        <TableHeaderColumn dataField="company">Company</TableHeaderColumn>
        <TableHeaderColumn dataField="email">Email</TableHeaderColumn>
</BootstrapTable>
```

It's a slightly different pattern with the label as a prop, but seems more reactish than rowSpan, though rowSpan is perhaps more within the bootstrap pattern. Just sharing an idea.

Anyway, I'm happy to help if I can with the existing implementation too. Please let me know if I can lend a hand!

**Comment by AllenFang** [comment]
@mattparrilla thanks your feedback, your consideration is also well, maybe it will be more easy to implement. Anyway, this PR is still under testing, so maybe you can improve this feature or implement span feature by your idea.

Let me know if you have any questions :)

**Comment by AllenFang** [comment]
@sumbad, thanks your contribution, it;s awesome that you give this feature, this PR already merged and released on ```v2.8.0```.  
Following are the commits that I fix some issue with colSpan feature,
https://github.com/AllenFang/react-bootstrap-table/commit/cf9514fc551a0dabfa3adf6aabdf773bde6b171c
https://github.com/AllenFang/react-bootstrap-table/commit/39ccae452d0b1a7e943edad3a182ee69f447da79
https://github.com/AllenFang/react-bootstrap-table/commit/6456488824d8e146fefb7343023b709fecadd00a
https://github.com/AllenFang/react-bootstrap-table/commit/f25fd8b89d9a6ad8bde68c75fd45956b76a4aa65

Thank you

**Pull request merged**
